name: commitizen

on:
  push:
    branches:
      - main

jobs:
  commitizen:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.15.1
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: body.md
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.cz.outputs.version }}
          body_path: body.md
